[package]
name = "zfs-gui-thing"
version = "0.1.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]
edition = "2018"

[dependencies]
vgtk = "0.1.0"
pretty_env_logger = "0.4.0"
anyhow = "1.0.26"
humansize = "1.1.0"
async-std = "1.5.0"
