[package]
name = "zfs-gui-thing"
version = "0.1.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vgtk = "0.1.0"
pretty_env_logger = "0.4.0"
anyhow = "1.0.26"
human_format = "1.0.3"
