[package]
name = "vgtk_treeview"
version = "0.1.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]
edition = "2018"

[dependencies]
vgtk = "0.2.0"
vgtk_treeview_macros = { path = "../vgtk_treeview_macros/" }
